
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-21 13:32:18 by Jeasu
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Joint.DLLFactory;
using Joint.IService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Joint.Web.Framework
{
    public partial class ServiceHelper
    {

		public static IBottleService GetBottleService
        {
            get { return ServiceFactory.Create<IBottleService>(); }
        }

		public static IConversationService GetConversationService
        {
            get { return ServiceFactory.Create<IConversationService>(); }
        }

		public static IModuleService GetModuleService
        {
            get { return ServiceFactory.Create<IModuleService>(); }
        }

		public static IPrivilegesService GetPrivilegesService
        {
            get { return ServiceFactory.Create<IPrivilegesService>(); }
        }

		public static IRelationPrivilegesRoleService GetRelationPrivilegesRoleService
        {
            get { return ServiceFactory.Create<IRelationPrivilegesRoleService>(); }
        }

		public static IRelationPrivilegesShopsService GetRelationPrivilegesShopsService
        {
            get { return ServiceFactory.Create<IRelationPrivilegesShopsService>(); }
        }

		public static IRelationPrivilegesStoresService GetRelationPrivilegesStoresService
        {
            get { return ServiceFactory.Create<IRelationPrivilegesStoresService>(); }
        }

		public static IRelationPrivilegesSystemService GetRelationPrivilegesSystemService
        {
            get { return ServiceFactory.Create<IRelationPrivilegesSystemService>(); }
        }

		public static IRelationPrivilegesUsersService GetRelationPrivilegesUsersService
        {
            get { return ServiceFactory.Create<IRelationPrivilegesUsersService>(); }
        }

		public static IRelationRoleModuleService GetRelationRoleModuleService
        {
            get { return ServiceFactory.Create<IRelationRoleModuleService>(); }
        }

		public static IRelationShopsModuleService GetRelationShopsModuleService
        {
            get { return ServiceFactory.Create<IRelationShopsModuleService>(); }
        }

		public static IRelationShopVersionModuleService GetRelationShopVersionModuleService
        {
            get { return ServiceFactory.Create<IRelationShopVersionModuleService>(); }
        }

		public static IRelationStoresModuleService GetRelationStoresModuleService
        {
            get { return ServiceFactory.Create<IRelationStoresModuleService>(); }
        }

		public static IRelationUserRoleService GetRelationUserRoleService
        {
            get { return ServiceFactory.Create<IRelationUserRoleService>(); }
        }

		public static IRelationUsersModuleService GetRelationUsersModuleService
        {
            get { return ServiceFactory.Create<IRelationUsersModuleService>(); }
        }

		public static IRoleService GetRoleService
        {
            get { return ServiceFactory.Create<IRoleService>(); }
        }

		public static IShopsService GetShopsService
        {
            get { return ServiceFactory.Create<IShopsService>(); }
        }

		public static IShopVersionService GetShopVersionService
        {
            get { return ServiceFactory.Create<IShopVersionService>(); }
        }

		public static IStoresService GetStoresService
        {
            get { return ServiceFactory.Create<IStoresService>(); }
        }

		public static IUserOperationLogService GetUserOperationLogService
        {
            get { return ServiceFactory.Create<IUserOperationLogService>(); }
        }

		public static IUsersService GetUsersService
        {
            get { return ServiceFactory.Create<IUsersService>(); }
        }

    }
}




