


//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-21 13:31:57 by Jeasu
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Joint.Entity;

namespace Joint.IService
{
	public partial interface IBottleService : IBaseService<Bottle>
    {
		
    }
	public partial interface IConversationService : IBaseService<Conversation>
    {
		
    }
	public partial interface IModuleService : IBaseService<Module>
    {
		
    }
	public partial interface IPrivilegesService : IBaseService<Privileges>
    {
		
    }
	public partial interface IRelationPrivilegesRoleService : IBaseService<RelationPrivilegesRole>
    {
		
    }
	public partial interface IRelationPrivilegesShopsService : IBaseService<RelationPrivilegesShops>
    {
		
    }
	public partial interface IRelationPrivilegesStoresService : IBaseService<RelationPrivilegesStores>
    {
		
    }
	public partial interface IRelationPrivilegesSystemService : IBaseService<RelationPrivilegesSystem>
    {
		
    }
	public partial interface IRelationPrivilegesUsersService : IBaseService<RelationPrivilegesUsers>
    {
		
    }
	public partial interface IRelationRoleModuleService : IBaseService<RelationRoleModule>
    {
		
    }
	public partial interface IRelationShopsModuleService : IBaseService<RelationShopsModule>
    {
		
    }
	public partial interface IRelationShopVersionModuleService : IBaseService<RelationShopVersionModule>
    {
		
    }
	public partial interface IRelationStoresModuleService : IBaseService<RelationStoresModule>
    {
		
    }
	public partial interface IRelationUserRoleService : IBaseService<RelationUserRole>
    {
		
    }
	public partial interface IRelationUsersModuleService : IBaseService<RelationUsersModule>
    {
		
    }
	public partial interface IRoleService : IBaseService<Role>
    {
		
    }
	public partial interface IShopsService : IBaseService<Shops>
    {
		
    }
	public partial interface IShopVersionService : IBaseService<ShopVersion>
    {
		
    }
	public partial interface IStoresService : IBaseService<Stores>
    {
		
    }
	public partial interface IUserOperationLogService : IBaseService<UserOperationLog>
    {
		
    }
	public partial interface IUsersService : IBaseService<Users>
    {
		
    }
	}





