


//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-21 13:31:51 by Jeasu
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Joint.Entity;

namespace Joint.IRepository
{
	
	public partial interface IBottleRepository : IBaseRepository<Bottle>
    {

    }
	
	public partial interface IConversationRepository : IBaseRepository<Conversation>
    {

    }
	
	public partial interface IModuleRepository : IBaseRepository<Module>
    {

    }
	
	public partial interface IPrivilegesRepository : IBaseRepository<Privileges>
    {

    }
	
	public partial interface IRelationPrivilegesRoleRepository : IBaseRepository<RelationPrivilegesRole>
    {

    }
	
	public partial interface IRelationPrivilegesShopsRepository : IBaseRepository<RelationPrivilegesShops>
    {

    }
	
	public partial interface IRelationPrivilegesStoresRepository : IBaseRepository<RelationPrivilegesStores>
    {

    }
	
	public partial interface IRelationPrivilegesSystemRepository : IBaseRepository<RelationPrivilegesSystem>
    {

    }
	
	public partial interface IRelationPrivilegesUsersRepository : IBaseRepository<RelationPrivilegesUsers>
    {

    }
	
	public partial interface IRelationRoleModuleRepository : IBaseRepository<RelationRoleModule>
    {

    }
	
	public partial interface IRelationShopsModuleRepository : IBaseRepository<RelationShopsModule>
    {

    }
	
	public partial interface IRelationShopVersionModuleRepository : IBaseRepository<RelationShopVersionModule>
    {

    }
	
	public partial interface IRelationStoresModuleRepository : IBaseRepository<RelationStoresModule>
    {

    }
	
	public partial interface IRelationUserRoleRepository : IBaseRepository<RelationUserRole>
    {

    }
	
	public partial interface IRelationUsersModuleRepository : IBaseRepository<RelationUsersModule>
    {

    }
	
	public partial interface IRoleRepository : IBaseRepository<Role>
    {

    }
	
	public partial interface IShopsRepository : IBaseRepository<Shops>
    {

    }
	
	public partial interface IShopVersionRepository : IBaseRepository<ShopVersion>
    {

    }
	
	public partial interface IStoresRepository : IBaseRepository<Stores>
    {

    }
	
	public partial interface IUserOperationLogRepository : IBaseRepository<UserOperationLog>
    {

    }
	
	public partial interface IUsersRepository : IBaseRepository<Users>
    {

    }
	
}





