
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-21 13:32:13 by Jeasu
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using Joint.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Joint.Web.Framework
{
    public static class ExtensionEntity
    {

		//==================Bottle拓展开始==================
		public static Bottle Add(this Bottle model)
        {
            return ServiceHelper.GetBottleService.AddEntity(model);
        }
        public static bool Update(this Bottle model)
        {
            return ServiceHelper.GetBottleService.UpdateEntity(model);
        }
        public static bool Delete(this Bottle model)
        {
            return ServiceHelper.GetBottleService.DeleteEntity(model.ID);
        }
		//==================Bottle拓展结束==================

		//==================Conversation拓展开始==================
		public static Conversation Add(this Conversation model)
        {
            return ServiceHelper.GetConversationService.AddEntity(model);
        }
        public static bool Update(this Conversation model)
        {
            return ServiceHelper.GetConversationService.UpdateEntity(model);
        }
        public static bool Delete(this Conversation model)
        {
            return ServiceHelper.GetConversationService.DeleteEntity(model.ID);
        }
		//==================Conversation拓展结束==================

		//==================Module拓展开始==================
		public static Module Add(this Module model)
        {
            return ServiceHelper.GetModuleService.AddEntity(model);
        }
        public static bool Update(this Module model)
        {
            return ServiceHelper.GetModuleService.UpdateEntity(model);
        }
        public static bool Delete(this Module model)
        {
            return ServiceHelper.GetModuleService.DeleteEntity(model.ID);
        }
		//==================Module拓展结束==================

		//==================Privileges拓展开始==================
		public static Privileges Add(this Privileges model)
        {
            return ServiceHelper.GetPrivilegesService.AddEntity(model);
        }
        public static bool Update(this Privileges model)
        {
            return ServiceHelper.GetPrivilegesService.UpdateEntity(model);
        }
        public static bool Delete(this Privileges model)
        {
            return ServiceHelper.GetPrivilegesService.DeleteEntity(model.ID);
        }
		//==================Privileges拓展结束==================

		//==================RelationPrivilegesRole拓展开始==================
		public static RelationPrivilegesRole Add(this RelationPrivilegesRole model)
        {
            return ServiceHelper.GetRelationPrivilegesRoleService.AddEntity(model);
        }
        public static bool Update(this RelationPrivilegesRole model)
        {
            return ServiceHelper.GetRelationPrivilegesRoleService.UpdateEntity(model);
        }
        public static bool Delete(this RelationPrivilegesRole model)
        {
            return ServiceHelper.GetRelationPrivilegesRoleService.DeleteEntity(model.ID);
        }
		//==================RelationPrivilegesRole拓展结束==================

		//==================RelationPrivilegesShops拓展开始==================
		public static RelationPrivilegesShops Add(this RelationPrivilegesShops model)
        {
            return ServiceHelper.GetRelationPrivilegesShopsService.AddEntity(model);
        }
        public static bool Update(this RelationPrivilegesShops model)
        {
            return ServiceHelper.GetRelationPrivilegesShopsService.UpdateEntity(model);
        }
        public static bool Delete(this RelationPrivilegesShops model)
        {
            return ServiceHelper.GetRelationPrivilegesShopsService.DeleteEntity(model.ID);
        }
		//==================RelationPrivilegesShops拓展结束==================

		//==================RelationPrivilegesStores拓展开始==================
		public static RelationPrivilegesStores Add(this RelationPrivilegesStores model)
        {
            return ServiceHelper.GetRelationPrivilegesStoresService.AddEntity(model);
        }
        public static bool Update(this RelationPrivilegesStores model)
        {
            return ServiceHelper.GetRelationPrivilegesStoresService.UpdateEntity(model);
        }
        public static bool Delete(this RelationPrivilegesStores model)
        {
            return ServiceHelper.GetRelationPrivilegesStoresService.DeleteEntity(model.ID);
        }
		//==================RelationPrivilegesStores拓展结束==================

		//==================RelationPrivilegesSystem拓展开始==================
		public static RelationPrivilegesSystem Add(this RelationPrivilegesSystem model)
        {
            return ServiceHelper.GetRelationPrivilegesSystemService.AddEntity(model);
        }
        public static bool Update(this RelationPrivilegesSystem model)
        {
            return ServiceHelper.GetRelationPrivilegesSystemService.UpdateEntity(model);
        }
        public static bool Delete(this RelationPrivilegesSystem model)
        {
            return ServiceHelper.GetRelationPrivilegesSystemService.DeleteEntity(model.ID);
        }
		//==================RelationPrivilegesSystem拓展结束==================

		//==================RelationPrivilegesUsers拓展开始==================
		public static RelationPrivilegesUsers Add(this RelationPrivilegesUsers model)
        {
            return ServiceHelper.GetRelationPrivilegesUsersService.AddEntity(model);
        }
        public static bool Update(this RelationPrivilegesUsers model)
        {
            return ServiceHelper.GetRelationPrivilegesUsersService.UpdateEntity(model);
        }
        public static bool Delete(this RelationPrivilegesUsers model)
        {
            return ServiceHelper.GetRelationPrivilegesUsersService.DeleteEntity(model.ID);
        }
		//==================RelationPrivilegesUsers拓展结束==================

		//==================RelationRoleModule拓展开始==================
		public static RelationRoleModule Add(this RelationRoleModule model)
        {
            return ServiceHelper.GetRelationRoleModuleService.AddEntity(model);
        }
        public static bool Update(this RelationRoleModule model)
        {
            return ServiceHelper.GetRelationRoleModuleService.UpdateEntity(model);
        }
        public static bool Delete(this RelationRoleModule model)
        {
            return ServiceHelper.GetRelationRoleModuleService.DeleteEntity(model.ID);
        }
		//==================RelationRoleModule拓展结束==================

		//==================RelationShopsModule拓展开始==================
		public static RelationShopsModule Add(this RelationShopsModule model)
        {
            return ServiceHelper.GetRelationShopsModuleService.AddEntity(model);
        }
        public static bool Update(this RelationShopsModule model)
        {
            return ServiceHelper.GetRelationShopsModuleService.UpdateEntity(model);
        }
        public static bool Delete(this RelationShopsModule model)
        {
            return ServiceHelper.GetRelationShopsModuleService.DeleteEntity(model.ID);
        }
		//==================RelationShopsModule拓展结束==================

		//==================RelationShopVersionModule拓展开始==================
		public static RelationShopVersionModule Add(this RelationShopVersionModule model)
        {
            return ServiceHelper.GetRelationShopVersionModuleService.AddEntity(model);
        }
        public static bool Update(this RelationShopVersionModule model)
        {
            return ServiceHelper.GetRelationShopVersionModuleService.UpdateEntity(model);
        }
        public static bool Delete(this RelationShopVersionModule model)
        {
            return ServiceHelper.GetRelationShopVersionModuleService.DeleteEntity(model.ID);
        }
		//==================RelationShopVersionModule拓展结束==================

		//==================RelationStoresModule拓展开始==================
		public static RelationStoresModule Add(this RelationStoresModule model)
        {
            return ServiceHelper.GetRelationStoresModuleService.AddEntity(model);
        }
        public static bool Update(this RelationStoresModule model)
        {
            return ServiceHelper.GetRelationStoresModuleService.UpdateEntity(model);
        }
        public static bool Delete(this RelationStoresModule model)
        {
            return ServiceHelper.GetRelationStoresModuleService.DeleteEntity(model.ID);
        }
		//==================RelationStoresModule拓展结束==================

		//==================RelationUserRole拓展开始==================
		public static RelationUserRole Add(this RelationUserRole model)
        {
            return ServiceHelper.GetRelationUserRoleService.AddEntity(model);
        }
        public static bool Update(this RelationUserRole model)
        {
            return ServiceHelper.GetRelationUserRoleService.UpdateEntity(model);
        }
        public static bool Delete(this RelationUserRole model)
        {
            return ServiceHelper.GetRelationUserRoleService.DeleteEntity(model.ID);
        }
		//==================RelationUserRole拓展结束==================

		//==================RelationUsersModule拓展开始==================
		public static RelationUsersModule Add(this RelationUsersModule model)
        {
            return ServiceHelper.GetRelationUsersModuleService.AddEntity(model);
        }
        public static bool Update(this RelationUsersModule model)
        {
            return ServiceHelper.GetRelationUsersModuleService.UpdateEntity(model);
        }
        public static bool Delete(this RelationUsersModule model)
        {
            return ServiceHelper.GetRelationUsersModuleService.DeleteEntity(model.ID);
        }
		//==================RelationUsersModule拓展结束==================

		//==================Role拓展开始==================
		public static Role Add(this Role model)
        {
            return ServiceHelper.GetRoleService.AddEntity(model);
        }
        public static bool Update(this Role model)
        {
            return ServiceHelper.GetRoleService.UpdateEntity(model);
        }
        public static bool Delete(this Role model)
        {
            return ServiceHelper.GetRoleService.DeleteEntity(model.ID);
        }
		//==================Role拓展结束==================

		//==================Shops拓展开始==================
		public static Shops Add(this Shops model)
        {
            return ServiceHelper.GetShopsService.AddEntity(model);
        }
        public static bool Update(this Shops model)
        {
            return ServiceHelper.GetShopsService.UpdateEntity(model);
        }
        public static bool Delete(this Shops model)
        {
            return ServiceHelper.GetShopsService.DeleteEntity(model.ID);
        }
		//==================Shops拓展结束==================

		//==================ShopVersion拓展开始==================
		public static ShopVersion Add(this ShopVersion model)
        {
            return ServiceHelper.GetShopVersionService.AddEntity(model);
        }
        public static bool Update(this ShopVersion model)
        {
            return ServiceHelper.GetShopVersionService.UpdateEntity(model);
        }
        public static bool Delete(this ShopVersion model)
        {
            return ServiceHelper.GetShopVersionService.DeleteEntity(model.ID);
        }
		//==================ShopVersion拓展结束==================

		//==================Stores拓展开始==================
		public static Stores Add(this Stores model)
        {
            return ServiceHelper.GetStoresService.AddEntity(model);
        }
        public static bool Update(this Stores model)
        {
            return ServiceHelper.GetStoresService.UpdateEntity(model);
        }
        public static bool Delete(this Stores model)
        {
            return ServiceHelper.GetStoresService.DeleteEntity(model.ID);
        }
		//==================Stores拓展结束==================

		//==================UserOperationLog拓展开始==================
		public static UserOperationLog Add(this UserOperationLog model)
        {
            return ServiceHelper.GetUserOperationLogService.AddEntity(model);
        }
        public static bool Update(this UserOperationLog model)
        {
            return ServiceHelper.GetUserOperationLogService.UpdateEntity(model);
        }
        public static bool Delete(this UserOperationLog model)
        {
            return ServiceHelper.GetUserOperationLogService.DeleteEntity(model.ID);
        }
		//==================UserOperationLog拓展结束==================

		//==================Users拓展开始==================
		public static Users Add(this Users model)
        {
            return ServiceHelper.GetUsersService.AddEntity(model);
        }
        public static bool Update(this Users model)
        {
            return ServiceHelper.GetUsersService.UpdateEntity(model);
        }
        public static bool Delete(this Users model)
        {
            return ServiceHelper.GetUsersService.DeleteEntity(model.ID);
        }
		//==================Users拓展结束==================

    }
}




