//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joint.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllPoi : BaseModel
    {
        public int ID { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public string MC { get; set; }
        public string PType { get; set; }
        public Nullable<double> Lng { get; set; }
        public Nullable<double> Lat { get; set; }
        public string MCPY { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
