//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joint.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bottle : BaseModel
    {
        public int ID { get; set; }
        public string Massage { get; set; }
        public string MassageKey { get; set; }
        public Nullable<int> FishingCount { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<int> FirstReplyUserID { get; set; }
        public Nullable<int> LastReplyUserID { get; set; }
        public string FirstReplyUserName { get; set; }
        public string LastReplyUserName { get; set; }
        public string CreateUserName { get; set; }
        public string LastReplyMassage { get; set; }
        public Nullable<System.DateTime> LastReplyTime { get; set; }
        public Nullable<System.DateTime> ReplyViewTime { get; set; }
        public Nullable<System.DateTime> CreateViewTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> Sexual { get; set; }
    }
}
