//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joint.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camera_info : BaseModel
    {
        public int ID { get; set; }
        public Nullable<double> CAMERA_ID { get; set; }
        public string CAMERA_NAME { get; set; }
        public string CAMERAINDEXCODE { get; set; }
        public string CDEPART { get; set; }
        public string CAREA { get; set; }
        public string CPLAT { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PWD { get; set; }
        public string CNAME { get; set; }
    }
}
