//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joint.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JingYuan : BaseModel
    {
        public int ID { get; set; }
        public string UnitCode { get; set; }
        public string XM { get; set; }
        public Nullable<short> State { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Lng { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<short> JYType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UserName { get; set; }
        public string GPSDeviceID { get; set; }
        public Nullable<short> BM { get; set; }
        public Nullable<short> IsOnline { get; set; }
        public string ShouTaiHao { get; set; }
        public string CameraIndexCode { get; set; }
        public string DeviceID { get; set; }
        public Nullable<short> IsFeatureUpdated { get; set; }
        public Nullable<short> IsNew { get; set; }
    }
}
