//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joint.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg : BaseModel
    {
        public int ID { get; set; }
        public string FromID { get; set; }
        public string FromXM { get; set; }
        public string ToID { get; set; }
        public string ToXM { get; set; }
        public string MsgContent { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
