//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joint.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privileges : BaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Privileges()
        {
            this.RelationPrivilegesRole = new HashSet<RelationPrivilegesRole>();
            this.RelationPrivilegesShops = new HashSet<RelationPrivilegesShops>();
            this.RelationPrivilegesStores = new HashSet<RelationPrivilegesStores>();
            this.RelationPrivilegesSystem = new HashSet<RelationPrivilegesSystem>();
            this.RelationPrivilegesUsers = new HashSet<RelationPrivilegesUsers>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string Code { get; set; }
        public string Value { get; set; }
        public Nullable<bool> UserShow { get; set; }
        public Nullable<bool> RoleShow { get; set; }
        public Nullable<bool> StoreShow { get; set; }
        public Nullable<bool> ShopShow { get; set; }
        public Nullable<bool> SystemShow { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Describe { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserID { get; set; }
    
        public virtual Module Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationPrivilegesRole> RelationPrivilegesRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationPrivilegesShops> RelationPrivilegesShops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationPrivilegesStores> RelationPrivilegesStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationPrivilegesSystem> RelationPrivilegesSystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationPrivilegesUsers> RelationPrivilegesUsers { get; set; }
    }
}
