//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joint.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationPrivilegesRole : BaseModel
    {
        public int ID { get; set; }
        public int RoleID { get; set; }
        public int PrivilegesID { get; set; }
        public int CreateUserID { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Privileges Privileges { get; set; }
        public virtual Role Role { get; set; }
    }
}
