//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joint.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stores : BaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stores()
        {
            this.RelationPrivilegesStores = new HashSet<RelationPrivilegesStores>();
            this.RelationStoresModule = new HashSet<RelationStoresModule>();
            this.Role = new HashSet<Role>();
            this.Users = new HashSet<Users>();
        }
    
        public int ID { get; set; }
        public int ShopId { get; set; }
        public string StoreName { get; set; }
        public string Phone { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Adress { get; set; }
        public string BankCard { get; set; }
        public string MapAdress { get; set; }
        public string LongitudeX { get; set; }
        public string LatitudeY { get; set; }
        public string StoresImage { get; set; }
        public string WifiName { get; set; }
        public string WifiPassword { get; set; }
        public bool IsShare { get; set; }
        public bool IsShowWeiXin { get; set; }
        public Nullable<bool> IsMainStore { get; set; }
        public string Remarks { get; set; }
        public bool Disabled { get; set; }
        public string Profile { get; set; }
        public string ShareExplain { get; set; }
        public string ReceiptLogo { get; set; }
        public string PrintRemark { get; set; }
        public Nullable<int> VirtualShopsID { get; set; }
        public string BankName { get; set; }
        public Nullable<int> AdminUserID { get; set; }
        public string ActvityName { get; set; }
        public Nullable<System.DateTime> ActvityEndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationPrivilegesStores> RelationPrivilegesStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationStoresModule> RelationStoresModule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Role { get; set; }
        public virtual Shops Shops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
