//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joint.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users : BaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.RelationPrivilegesUsers = new HashSet<RelationPrivilegesUsers>();
            this.RelationUserRole = new HashSet<RelationUserRole>();
            this.RelationUsersModule = new HashSet<RelationUsersModule>();
            this.UserOperationLog = new HashSet<UserOperationLog>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool NeedAccount { get; set; }
        public string PasswordSalt { get; set; }
        public string Email { get; set; }
        public string RealName { get; set; }
        public string WorkNum { get; set; }
        public Nullable<int> WorkTypeID { get; set; }
        public string Phone { get; set; }
        public string TEL { get; set; }
        public string QQ { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public string Photo { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<bool> WeiXinVisible { get; set; }
        public string WeiXinOpenID { get; set; }
        public string WeiXinOpenName { get; set; }
        public Nullable<bool> WeiXinOrderNotice { get; set; }
        public Nullable<bool> WeiXinAppointmentNotice { get; set; }
        public string Idcard { get; set; }
        public string IdcardPhoto { get; set; }
        public Nullable<int> ShopsID { get; set; }
        public Nullable<int> DefaultStoreID { get; set; }
        public Nullable<int> LoginTimes { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<bool> IsIntention { get; set; }
        public int CreateUserID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool Disabled { get; set; }
        public Nullable<bool> IsCouponNotice { get; set; }
        public string WeiXinAutoLoginOpenID { get; set; }
        public string LastLoginIP { get; set; }
        public string LastLoginArea { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Sexual { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<double> GoldCoin { get; set; }
        public Nullable<int> Fishing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationPrivilegesUsers> RelationPrivilegesUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationUserRole> RelationUserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationUsersModule> RelationUsersModule { get; set; }
        public virtual Stores Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOperationLog> UserOperationLog { get; set; }
    }
}
