


//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-02-21 13:32:02 by Jeasu
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Joint.Entity;
using Joint.IRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Joint.Repository
{	
	public partial class BottleRepository : BaseRepository<Bottle>, IBottleRepository
    {
    }
	public partial class ConversationRepository : BaseRepository<Conversation>, IConversationRepository
    {
    }
	public partial class ModuleRepository : BaseRepository<Module>, IModuleRepository
    {
    }
	public partial class PrivilegesRepository : BaseRepository<Privileges>, IPrivilegesRepository
    {
    }
	public partial class RelationPrivilegesRoleRepository : BaseRepository<RelationPrivilegesRole>, IRelationPrivilegesRoleRepository
    {
    }
	public partial class RelationPrivilegesShopsRepository : BaseRepository<RelationPrivilegesShops>, IRelationPrivilegesShopsRepository
    {
    }
	public partial class RelationPrivilegesStoresRepository : BaseRepository<RelationPrivilegesStores>, IRelationPrivilegesStoresRepository
    {
    }
	public partial class RelationPrivilegesSystemRepository : BaseRepository<RelationPrivilegesSystem>, IRelationPrivilegesSystemRepository
    {
    }
	public partial class RelationPrivilegesUsersRepository : BaseRepository<RelationPrivilegesUsers>, IRelationPrivilegesUsersRepository
    {
    }
	public partial class RelationRoleModuleRepository : BaseRepository<RelationRoleModule>, IRelationRoleModuleRepository
    {
    }
	public partial class RelationShopsModuleRepository : BaseRepository<RelationShopsModule>, IRelationShopsModuleRepository
    {
    }
	public partial class RelationShopVersionModuleRepository : BaseRepository<RelationShopVersionModule>, IRelationShopVersionModuleRepository
    {
    }
	public partial class RelationStoresModuleRepository : BaseRepository<RelationStoresModule>, IRelationStoresModuleRepository
    {
    }
	public partial class RelationUserRoleRepository : BaseRepository<RelationUserRole>, IRelationUserRoleRepository
    {
    }
	public partial class RelationUsersModuleRepository : BaseRepository<RelationUsersModule>, IRelationUsersModuleRepository
    {
    }
	public partial class RoleRepository : BaseRepository<Role>, IRoleRepository
    {
    }
	public partial class ShopsRepository : BaseRepository<Shops>, IShopsRepository
    {
    }
	public partial class ShopVersionRepository : BaseRepository<ShopVersion>, IShopVersionRepository
    {
    }
	public partial class StoresRepository : BaseRepository<Stores>, IStoresRepository
    {
    }
	public partial class UserOperationLogRepository : BaseRepository<UserOperationLog>, IUserOperationLogRepository
    {
    }
	public partial class UsersRepository : BaseRepository<Users>, IUsersRepository
    {
    }
	
}





